sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ddu0191/react-test -f ./client/Dockerfile.dev ./client
  - docker run --user='root' --entrypoint chown ddu0191/react-test -R 1000:1000 .

script:
  - docker run -e CI=true ddu0191/react-test npm test
  - docker build -t ddu0191/multi-client:v1 ./client
  - docker build -t ddu0191/multi-nginx:v1 ./nginx
  - docker build -t ddu0191/multi-server:v1 ./server
  - docker build -t ddu0191/multi-worker:v1 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub.
  - docker push ddu0191/multi-client:v1
  - docker push ddu0191/multi-nginx:v1
  - docker push ddu0191/multi-server:v1
  - docker push ddu0191/multi-worker:v1
